all: avltree binary binarytree linear rnbtree treap

avltree: avltree.c
	gcc -O3 -DNDEBUG -o avltree avltree.c

binary: binary.c
	gcc -O3 -DNDEBUG -o binary binary.c

binarytree: binarytree.c
	gcc -O3 -DNDEBUG -o binarytree binarytree.c

linear: linear.c
	gcc -O3 -DNDEBUG -o linear linear.c

rnbtree: rnbtree.c
	gcc -O3 -DNDEBUG -o rnbtree rnbtree.c

treap: treap.c
	gcc -O3 -DNDEBUG -o treap treap.c

clean:
	rm -f avltree binary binarytree linear rnbtree treap
